version: '3.8'
services:

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.7.0
    restart: always
    container_name: elasticsearch
    ports:
      - "9200:9200"
    environment:
      discovery.type: "single-node"
      ES_JAVA_OPTS: "-Xms2g -Xmx2g"
      xpack.monitoring.enabled: "true"
    volumes:
      - ./esdata:/var/lib/elasticsearch/data
    healthcheck:
      test: curl -s http://elasticsearch:9200 >/dev/null || exit 1
      interval: 10s
      timeout: 15s
      retries: 3

  kibana:
    restart: always
    image: docker.elastic.co/kibana/kibana:7.7.0
    container_name: kibana
    ports:
      - "5601:5601"
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
    depends_on:
      elasticsearch:
        condition: service_healthy

  api:
    container_name: spring-elastic-stack_api
    restart: always
    build:
      dockerfile: config/Dockerfile
      context: .
    ports:
      - "8091:8091"
    environment:
      - "SPRING_PROFILES_ACTIVE=prod"
    volumes:
      - api_data:/usr/local/spring_elastic_stack
    depends_on:
      elasticsearch:
        condition: service_healthy



volumes:
  esdata:
    driver: local
  api_data:
    driver: local