pipeline {
    agent any
    stages {
        stage("Limpeza dos containers"){
            steps {
                sh 'docker system prune -a --volumes -f'
            }
        }
        stage("Build da aplicação"){
            steps {
                sh 'mvn clean package -DskipTests=true'
            }
        }
        stage("Subindo a aplicação.") {
            steps {
                sh 'docker compose up --build --force-recreate --no-color --wait'
                sh 'docker compose ps'
            }
        }
    }
}